### PR TITLE
Upgrade 'nan' to 2.20.0

### PR DESCRIPTION
**Pull request by andy-finale**
The only manual change is to `package.json`, after that I ran:
```
rm -r node_modules
rm package-lock.json
/var/fwcs/bin/node-v22.4.0/bin/npm install
```

(I also tested on node 12, and the `package-lock.json` and `package.json` files were different, but the package contents were the same.)

### CODE REVIEW

**Review by briannielson — CHANGES_REQUESTED** [review]
This needs a CCC checklist. Also, can you manually test the native builds? I'm assuming this library is used for node-gyp...

**Comment by briannielson** [comment]
Ah, this is rconsole's repo... I'm not sure how we deploy changes for rconsole. I'll look into this and see what we can do.

**Comment by andy-finale** [comment]
It's worth noting that the same `rconsole` is installed globally and used by the `www` and `stream` code, as well as `pm2`. The reason I'm updating `nan` is to support building with newer versions of Node; I don't expect this will have any effect on older versions.

**Comment by andy-finale** [comment]
I ran a local test to confirm that this will still work with node 12:
```
cd /var/fwcs/bin/node-v12.16.3/lib/node_modules/rconsole
git clean -xfd # clean build
sudo git checkout ah-upgrade-nan
sudo rm -r node_modules
sudo /var/fwcs/bin/node-v12.16.3/bin/node /var/fwcs/bin/node-v12.16.3/bin/npm install
sudo /var/fwcs/bin/node-v12.16.3/bin/node /var/fwcs/bin/node-v12.16.3/bin/npm run install
cd ~/dev/server
make restart
tail /var/log/app-account-0.log
```
I also added a log message at the bottom of `rconsole.js` so I could verify that it's using the new code.

Let's talk tomorrow about a deployment plan.

**Comment by andy-finale** [comment]
I changed the base branch to `node22`, so this is no longer a CCC.
The plan is to make the install script for node 22 use the `node22` branch.

**Review by briannielson — APPROVED** [review]

**Review by chondl — APPROVED** [review]

**Pull request merged**
